export const inventory = {

    'Absolut citron': { alcohol: true },
    'Ale': { alcohol: true },
    'Amaretto': { alcohol: true },
    'Apple brandy': { alcohol: true },
    'Applejack': { alcohol: true },
    'Baileys irish cream': { alcohol: true },
    'Blackberry brandy': { alcohol: true },
    'Bourbon': { alcohol: true },
    'Brandy': { alcohol: true },
    'Champagne': { alcohol: true },
    'Cherry brandy': { alcohol: true },
    'Chocolate liqueur': { alcohol: true },
    'Cider': { alcohol: true },
    'Cognac': { alcohol: true },
    'Creme de Cacao': { alcohol: true },
    'Creme de Cassis': { alcohol: true },
    'Dark Rum': { alcohol: true },
    'Dubonnet Rouge': { alcohol: true },
    'Everclear': { alcohol: true },
    'Firewater': { alcohol: true },
    'Galliano': { alcohol: true },
    'Gin': { alcohol: true },
    'Irish cream': { alcohol: true },
    'Irish whiskey': { alcohol: true },
    'Jack Daniels': { alcohol: true },
    'Johnnie Walker': { alcohol: true },
    'Kahlua': { alcohol: true },
    'Lager': { alcohol: true },
    'Lemon Vodka': { alcohol: true },
    'Light rum': { alcohol: true },
    'Midori melon liqueur': { alcohol: true },
    'Ouzo': { alcohol: true },
    'Peach Vodka': { alcohol: true },
    'Peppermint schnapps': { alcohol: true },
    'Pisco': { alcohol: true },
    'Port': { alcohol: true },
    'Red wine': { alcohol: true },
    'Ricard': { alcohol: true },
    'Rum': { alcohol: true },
    'Scotch': { alcohol: true },
    'Sloe gin': { alcohol: true },
    'Southern Comfort': { alcohol: true },
    'Spiced rum': { alcohol: true },
    'Strawberry schnapps': { alcohol: true },
    'Tequila': { alcohol: true },
    'Triple Sec': { alcohol: true },
    'Vodka': { alcohol: true },
    'Whiskey': { alcohol: true },


   'Angelica root': { alcohol: false },
    'Apple juice': { alcohol: false },
    'Berries': { alcohol: false },
    'Brandy': { alcohol: true },
    'Cantaloupe': { alcohol: false },
    'Carbonated water': { alcohol: false },
    'Chocolate': { alcohol: false },
    'Chocolate syrup': { alcohol: false },
    'Cocoa powder': { alcohol: false },
    'Coffee': { alcohol: false },
    'Cranberries': { alcohol: false },
    'Egg': { alcohol: false },
    'Espresso': { alcohol: false },
    'Ginger': { alcohol: false },
    'Grapes': { alcohol: false },
    'Grapefruit juice': { alcohol: false },
    'Heavy cream': { alcohol: false },
    'Kiwi': { alcohol: false },
    'Lemon': { alcohol: false },
    'Lemonade': { alcohol: false },
    'Lemon juice': { alcohol: false },
    'Mango': { alcohol: false },
    'Milk': { alcohol: false },
    'Orange': { alcohol: false },
    'Peach nectar': { alcohol: false },
    'Pineapple juice': { alcohol: false },
    'Sherry': { alcohol: false },
    'Sugar': { alcohol: false },
    'Sugar syrup': { alcohol: false },
    'Strawberries': { alcohol: false },
    'Tomato juice': { alcohol: false },
    'Water': { alcohol: false },
    'Yoghurt': { alcohol: false }






};
